### ISSUE TITLE
an ActivityNotFoundException bug

### ISSUE THREAD

**Issue by tingsu** [scoutant/blokish#13]
Hi, thanks for developing this interesting app. We recently tested this app by an automated Android GUI testing tool developed by our research team. We found the app could run into an "ActivityNotFoundException" error after executing the following actions: 

start the app -> press menu -> click "help" item -> click the video

We tested this app on a Android phone with SDK 4.4.4, and tested both a previous old version and the newest version. In both cases, the app crashed under the above sequence.

Here is the log:

E/AndroidRuntime( 3703): FATAL EXCEPTION: main
E/AndroidRuntime( 3703): Process: a3e.process, PID: 3703
E/AndroidRuntime( 3703): android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=vnd.youtube://3Q7ow07uaMw }
E/AndroidRuntime( 3703):    at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1632)
E/AndroidRuntime( 3703):    at android.app.Instrumentation.execStartActivity(Instrumentation.java:1424)
E/AndroidRuntime( 3703):    at android.app.Activity.startActivityForResult(Activity.java:3553)
E/AndroidRuntime( 3703):    at android.app.Activity.startActivityForResult(Activity.java:3514)
E/AndroidRuntime( 3703):    at android.app.Activity.startActivity(Activity.java:3756)
E/AndroidRuntime( 3703):    at android.app.Activity.startActivity(Activity.java:3724)
E/AndroidRuntime( 3703):    at org.scoutant.blokish.Help$1.onClick(Help.java:19)
E/AndroidRuntime( 3703):    at android.view.View.performClick(View.java:4444)
E/AndroidRuntime( 3703):    at android.view.View$PerformClick.run(View.java:18445)
E/AndroidRuntime( 3703):    at android.os.Handler.handleCallback(Handler.java:733)
E/AndroidRuntime( 3703):    at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime( 3703):    at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime( 3703):    at android.app.ActivityThread.main(ActivityThread.java:5135)
E/AndroidRuntime( 3703):    at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 3703):    at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime( 3703):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:795)
E/AndroidRuntime( 3703):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:611)
E/AndroidRuntime( 3703):    at dalvik.system.NativeStart.main(Native Method)

The suspicious code may be in Help.java:

<img width="719" alt="screen shot 2016-04-13 at 11 26 21 am" src="https://cloud.githubusercontent.com/assets/3156978/14481921/ef54bfae-0169-11e6-86c4-f9345f1e02b0.png">

Could you please take a look and confirm this bug? Thanks!
Ting Su

**Comment by scoutant** [comment]
Absolutely. A smartphone without Youtube app installed will not resolve the intent. I will put a http Uri instead in next release.
Thanks.

**Comment by tingsu** [comment]
Thanks, scoutant.
